### ISSUE TITLE
Compression of image header

### ISSUE THREAD

**Issue by paulmsmith** [oneteamgov/website#2]
The large header image on the homepage of oneteamgov is badly degraded. Consider resizing and compressing with Guetzli.

**Comment by soniaturcotte** [comment]
I have the adobe suite, which has good image compression options. Can do this if you send me the original image.

**Comment by paulmsmith** [comment]
![otgcomp](https://user-images.githubusercontent.com/57055/30475575-3130d6c2-99ff-11e7-99b3-634d92e2e377.jpg)

Image attached. It's bigger than some devices see.. One day soon I will want to switch it out to be a responsive image (different sizes for different viewport widths) but for now it's one image for all devices. Time being the issue I have at the minute.

**Comment by soniaturcotte** [comment]
Do you have the original design file?

**Comment by paulmsmith** [comment]
The original file is for Affinity Designer (I no longer have an Adobe Account). You could get the trial for it perhaps? I will upload that to somewhere, it's rather large.

**Comment by paulmsmith** [comment]
Although to be honest. If you or anybody else want to have a go at doing something different for that masthead? Feel free! Thanks @soniaturcotte 👍

**Comment by paulmsmith** [comment]
I've recompressed the current one for now. Will send the large file.

**Comment by paulmsmith** [comment]
Uploaded [original](http://files.paulsmith.site/montage.zip) for those that want it. You will need [Affinity Designer](https://affinity.serif.com/en-gb/designer/)
